### ISSUE TITLE
kasini3000 using deprecated SSH key format

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#11]
config.ps1, gtnode.ps1 and others refer to .ssh/id_rsa

RSA key format for SSH usage is being deprecated by OpenSSH.

https://www.openssh.com/txt/release-8.2

Suggest update to better algorithm, for example ECDSA or Ed25519.

**Comment by kasini3000** [comment]
Through my research, I found that the problem is rsa-sha1, but it has nothing to do with the ssh client, nothing to do with kasini3000, nothing to do with keyfile format.

see:
https://superuser.com/questions/1390593/how-to-generate-ssh-rsa-key-instead-of-rsa-sha2-512

----

gx更新主控机ssh秘钥1.ps1
gx更新主控机ssh秘钥2z.ps1
jl建立主控机ssh秘钥1z.ps1

only create rsa4096 key-file ,It is more secure than the default 2048 secret key of the current linux distribution.
It will not be changed within 5 years.

**Comment by kasini3000** [comment]
add Ed25519 key-file format ,set it to default on October 2024.
