### ISSUE TITLE
Thank you for Code Review

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#16]
Hi,

Thanks for the invite to kick the tyres of your project. It is certainly interesting and I wish you well with it.

You have made design choices along the way as any developer must do. 

For me the two main roadblocks to using the project are the installation, mainly using git to install binary packages, and the use of root on Linux. But you are free to make your choices in your project.

Thanks again

**Comment by kasini3000** [comment]
Well, have a nice day. Here's a joke for you.
Entering the kitchen of the hotel, you will find the chef is cutting vegetables with a knife.
In order to prevent chefs from going crazy and cutting people with knives, the manager requires each chef to bring handcuffs to cut vegetables.

on linux master pc,send "ssh xxx@ip cmd" via root permission will let you linux  controlled by hacker ? ---ha ha ~

**Comment by rhubarb-geek-nz** [comment]
Why do people wear seatbelts when driving cars, are they intending to crash?

**Comment by kasini3000** [comment]
Kasini3000 is like street food in developing countries:
1 Clean and sanitary
2. You can eat when you pick it up. You don't need knives and forks, tables or formal clothes== Out of the box
3 Very delicious==powerful.

And you are deeply worried about heavy metals and nuclear radiation in food. 
You said, "Put the chef with the knife in the cage immediately!"

**Comment by kasini3000** [comment]
Why don't you suggest to the ps team :
“new-pssession should not run on the root permission” ?

**Comment by rhubarb-geek-nz** [comment]
> Why don't you suggest to the ps team :
> “new-pssession should not run on the root permission” ?

You are missing the point. The danger is not the single call to New-PSSession. The risk is every single line of your code that is running as root.
